# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DVSOMEIP_INTERNAL_SUPPRESS_DEPRECATED -DVSOMEIP_VERSION=\"3.4.9.1\" -D_GTHREAD_USE_MUTEX_INIT_FUNC -D_GTHREAD_USE_RECURSIVE_MUTEX_INIT_FUNC -Dvsomeip3_EXPORTS

CXX_INCLUDES = -I/home/orca/Downloads/vsomeip-3.4.9-r1/interface

CXX_FLAGS =  -DVSOMEIP_BOOST_VERSION=107400 -DWITHOUT_SYSTEMD  -pie -Wno-tsan -Wl,-z,relro,-z,now -D_GLIBCXX_USE_NANOSLEEP -pthread -O -Wall -Wextra -Wformat -Wformat-security -Wconversion -fexceptions -fstrict-aliasing -fstack-protector-strong -fasynchronous-unwind-tables -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wpedantic -Werror=stringop-overflow=0 -fPIE -g  -std=c++14  -Wl,-export-dynamic -Wl,--version-script=/home/orca/Downloads/vsomeip-3.4.9-r1/exportmap.gcc -O2 -g -DNDEBUG -fPIC

